# Generated by Django 2.1.5 on 2019-02-15 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_auto_20190214_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author',
            field=models.CharField(default='username', max_length=200),
        ),
    ]
