# Generated by Django 2.1.5 on 2019-02-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=5),
        ),
    ]
